#pragma once

#define SERVO_AMOUNT 6
#define BASE_LEFT -90
#define BASE_MIDDLE 0
#define BASE_RIGHT 90
#define SHOULDER_BACKWARDS -30
#define SHOULDER_VERTICAL 0
#define SHOULDER_HORIZONTAL 90
#define ELBOW_STRAIGHT -90
#define ELBOW_SHARPDOWN 0
#define ELBOW_INWARDS 45
#define WRIST_UP 90
#define WRIST_STRAIGHT 0
#define WRIST_DOWN -90
#define GRIPPER_OPEN 90
#define GRIPPER_CLOSED -90
#define WRIST_ROTATE_LEFT -90
#define WRIST_ROTATE_MIDDLE 0
#define WRIST_ROTATE_RIGHT 90

#define BASE_ROTOR_PARK 0
#define SHOULDER_PARK 40
#define ELBOW_PARK 33
#define WRIST_PARK -90
#define GRIPPER_PARK 90
#define WRIST_ROTATE_PARK 0

#define BASE_ROTOR_READY 0
#define SHOULDER_READY 0
#define ELBOW_READY 0
#define WRIST_READY 0
#define GRIPPER_READY 0
#define WRIST_ROTATE_READY 0

#define BASE_ROTOR_STRAIGHTUP 0
#define SHOULDER_STRAIGHTUP 0
#define ELBOW_STRAIGHTUP -80
#define WRIST_STRAIGHTUP 0
#define GRIPPER_STRAIGHTUP 90
#define WRIST_ROTATE_STRAIGHTUP 90

#define TIME_PARK_IN_US 5000
#define TIME_READY_IN_US 5000
#define TIME_STRAIGHTUP_IN_US 5000